networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "6379:6379" 
    networks:
      - app-tier

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db 
    networks:
      - app-tier

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
      ME_CONFIG_BASICAUTH: false
    networks:
      - app-tier

  backend:
    build:
      context: ./backend/banking-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/bankingBD
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis
    networks:
      - app-tier

  frontend:
    build:
      context: ./frontend/banking-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-tier